#!/bin/bash

read -p "Enter project name : " project_name

for name in reset_database restore_latest_db start_local_postgres
do
  mv $name $name.bak
  sed 's/{{ project_name }}/${project_name}/g' $name.bak > $name
  chmod +x $name
  rm $name.bak
done

